import { app } from 'electron';
import * as fs from 'fs';
import * as path from 'path';

/**
 * The Copilot CLI inspects `process.versions.electron` to decide how to parse
 * its argv. When launched under Electron with `ELECTRON_RUN_AS_NODE=1` the
 * binary behaves as Node, but `process.versions.electron` is still set, so the
 * CLI takes its Electron code path and fails with:
 *   "error: too many arguments. Expected 0 arguments but got 1."
 *
 * To work around this, we materialize a small ESM wrapper that strips the
 * Electron runtime markers from `process.versions` and then dynamic-imports
 * the real CLI. The SDK is pointed at this wrapper instead of the real CLI.
 *
 * The wrapper is regenerated on every call so updates to its content always
 * take effect across app upgrades.
 */
export function buildShimContent(realCliPath: string): string {
  const escaped = realCliPath.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  // CommonJS wrapper: the SDK's spawn logic only treats `.js` as needing Node
  // (it tries to exec `.mjs` directly, which yields EFTYPE on Windows).
  // We use dynamic `import()` because the real CLI is ESM.
  return `// Auto-generated by whim. Do not edit.
// Strips Electron runtime markers so the Copilot CLI behaves like plain Node.
const { pathToFileURL } = require('node:url');
delete process.versions.electron;
delete process.versions.chrome;
const target = '${escaped}';
import(pathToFileURL(target).href).catch((err) => {
  process.stderr.write('[cli-shim] Failed to import target CLI: ' + (err && err.stack || err) + '\\n');
  process.exit(1);
});
`;
}

/**
 * Returns the path to a CJS wrapper that should be spawned in place of a
 * JavaScript CLI entrypoint under Electron. Re-writes the file on every call
 * so the wrapper content stays in sync with the current Whim build.
 *
 * Native executables are spawned directly and do not need the wrapper.
 */
export function getCliShimPath(realCliPath: string): string | null {
  if (!realCliPath) return null;
  const pathApi = process.platform === 'win32' ? path.win32 : path.posix;
  if (pathApi.extname(realCliPath).toLowerCase() !== '.js') return null;

  const userData = app.getPath('userData');
  const shimDir = pathApi.join(userData, 'cli-shim');
  // The SDK only treats `.js` files as JavaScript that needs to be run via
  // Node; `.mjs` is spawned directly (EFTYPE on Windows). Keep the `.js`
  // extension and use CJS syntax in `buildShimContent`.
  const shimPath = pathApi.join(shimDir, 'cli-electron-shim.js');

  try {
    fs.mkdirSync(shimDir, { recursive: true });
    fs.writeFileSync(pathApi.join(shimDir, 'package.json'), '{"type":"commonjs"}\n', 'utf8');
    fs.writeFileSync(shimPath, buildShimContent(realCliPath), 'utf8');
  } catch (err) {
    console.warn('[cli-shim] Failed to materialize Electron shim:', err);
    return null;
  }

  return shimPath;
}
